namespace CRS.Models.Emails;

/// <summary>
/// Email model for internal staff notifications about invoices.
/// </summary>
public class InvoiceStaffNotificationEmail
{
    public required Invoice Invoice { get; set; }
    
    public ReserveStudy? ReserveStudy { get; set; }
    
    public required string BaseUrl { get; set; } = string.Empty;
    
    /// <summary>
    /// The type of notification.
    /// </summary>
    public InvoiceNotificationType NotificationType { get; set; }
    
    /// <summary>
    /// Optional additional details about the notification.
    /// </summary>
    public string? Details { get; set; }
    
    /// <summary>
    /// The previous invoice that triggered this notification (for auto-generated).
    /// </summary>
    public Invoice? PreviousInvoice { get; set; }
}

public enum InvoiceNotificationType
{
    /// <summary>
    /// A new invoice was auto-generated from a paid milestone.
    /// </summary>
    AutoGenerated,
    
    /// <summary>
    /// An invoice was paid via Stripe.
    /// </summary>
    PaymentReceived,
    
    /// <summary>
    /// An invoice became overdue.
    /// </summary>
    BecameOverdue
}
