using Coravel.Mailer.Mail;
using Horizon.Models.Emails;

namespace Horizon.Models.Email;

/// <summary>
/// Mailable for sending internal staff notifications about invoices.
/// </summary>
public class InvoiceStaffNotificationMailable : Mailable<InvoiceStaffNotificationEmail>
{
    private readonly InvoiceStaffNotificationEmail _notification;
    private readonly string _recipientEmail;

    public InvoiceStaffNotificationMailable(InvoiceStaffNotificationEmail notification, string recipientEmail)
    {
        _notification = notification;
        _recipientEmail = recipientEmail;
    }

    public override void Build()
    {
        var invoice = _notification.Invoice;
        var communityName = _notification.ReserveStudy?.Community?.Name ?? invoice.BillToName ?? "Client";

        var subject = _notification.NotificationType switch
        {
            InvoiceNotificationType.AutoGenerated => 
                $"[Auto-Generated] New Invoice #{invoice.InvoiceNumber} for {communityName}",
            InvoiceNotificationType.PaymentReceived => 
                $"Payment Received: Invoice #{invoice.InvoiceNumber} - {communityName}",
            InvoiceNotificationType.BecameOverdue => 
                $"[Alert] Invoice #{invoice.InvoiceNumber} is now overdue - {communityName}",
            _ => $"Invoice Notification: #{invoice.InvoiceNumber}"
        };

        this.To(_recipientEmail)
            .From("no-reply@reservecloud.com")
            .Subject(subject)
            .View("~/Components/EmailTemplates/InvoiceStaffNotification.cshtml", _notification);
    }
}
